### ISSUE TITLE
error if csv filename begins with a number

### ISSUE THREAD

**Issue by judell** [turbot/steampipe-plugin-csv#18]
To reproduce, convert a file that works properly, with a name like `foo.csv`, to instead be `1foo.csv`. 

> Error: syntax error at or near "1" (SQLSTATE 42601)

**Comment by judell** [comment]
You can do this:

> select * from csv.foo

But not:

> select * from csv.1foo

It has to be:

> select * from csv."1foo"

**Comment by cbruno10** [comment]
@judell I believe that's normal Postgres behaviour, as it expects table names to start with a lowercase letter or an underscore (there may be other symbols they accept). If the table name does not start with one these characters, you need to wrap it in double quotes.

I'm closing this issue as I don't believe it's a bug in the CSV plugin, but instead expected behaviour from Postgres.

**Comment by judell** [comment]
Yeah I did not mean to reopen, sorry.
