### ISSUE TITLE
CSV plugin loads csv tables from prior working directory when issues encountered

### ISSUE THREAD

**Issue by Eric-Hacker** [turbot/steampipe-plugin-csv#49]
**Describe the bug**
When steampipe with the csv plugin has been run in one directory successfully, quit, and then launched from a different directory with a csv file that contains a "_ctx" column , it will load the csv tables from the prior directory with no other warnings to the terminal. This occurs even if the csv.spc is set to only load from the new directory. No steampipe processes were found running between runs.

**Steampipe version (`steampipe -v`)**
steampipe version 0.17.4

**To reproduce**
$ cd /users/me/turbot
$ steampipe query --output csv "select * from googledirectory_user" > google_users
$ mv google_users google_users.csv
#### directory contains day4.csv see https://github.com/Eric-Hacker/AOC22/tree/main/Day4 for example
$ cd /users/me/aoc/day4
$ steampipe query "select * from day4.csv"
#### whoops, how time flies, better get some real work done
$ cd /users/me/turbot
$ steampipe query
> .inspect cdv
+-------+-----------------------------------------------------------+
| table | description                                               |
+-------+-----------------------------------------------------------+
| day4  | CSV file at /Users/me/aoc/day4/day4.csv                                   |
+-------+-----------------------------------------------------------+
#### think, hmm, I guess I wasn't meant to get work done today, maybe I should go back to working on AOC

**Expected behavior**
Should be loading tables from the current directory or give a warning if there are issues.

**Comment by cbruno10** [comment]
Hey @Eric-Hacker , thanks for raising this issue!

For the older CSV files being loaded, here's what I believe is happening:
- Steampipe is run in the first directory and all CSV files are loaded correctly and new tables are created in the schema
- You move to another directory that contains one or more CSV files with `_ctx` columns
- Steampipe is run in the new directory, but the CSV plugin fails initialization because of the duplicate `_ctx` column
- Even though the CSV plugin failed initialization in the previous step, the previous CSV tables in the schema are still present, since Steampipe does not remove previously created tables for a plugin if it fails initialization

Based on the behaviours above, I think this is why it looks like Steampipe is reloading the previous directory's files, but it's really just keeping the same tables from before.

@kaidaguerre Is my understanding of plugin schemas correct, in particular around when a plugin initializes successfully, but then later fails to initialize? 

@Eric-Hacker I think the most helpful fix would be better handling of duplicate columns, in particular around the `_ctx` column, which is the only column Steampipe attempts to create in all tables by default today. This is something we're actively looking into it and would like to avoid hard failures even if one or more CSV files have the `_ctx` column already.

**Comment by cbruno10** [comment]
@Eric-Hacker If you're still having issues, please let us know! I'm closing this issue for now, but feel free to re-open.
